version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "numpy"
        versions: ["1.12.x"]
      - dependency-name: "numpy"
      - dependency-name: "boto3"
      - dependency-name: "numpy"
        update-types: ["version-update:semver-minor"]
