version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "boto3"
      - dependency-name: "numpy"
        versions: ["1.11.3"]
        update-types: ["version-update:semver-patch"]
      - dependency-name: "numpy"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "pep8"
        update-types: ["version-update:semver-patch"]
